# -*- coding: utf-8 -*-
"""Self-host Fraunces and Archivo instead of loading them from Google Fonts.

Loading fonts from fonts.googleapis.com sends every visitor's IP address to
Google on every page view (LG Muenchen I, 3 O 17493/20). The files are
SIL Open Font License, so they can live next to the site.

Keeps the latin and latin-ext subsets (latin-ext carries ș ț ă â î for
Romanian and the German/Italian accents); drops vietnamese.

    python tools/build-fonts.py
"""
import io
import os
import re
import urllib.request

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36"
CSS_URL = ("https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,340..640;"
           "1,9..144,340..640&family=Archivo:wght@400;500;600&display=swap")
KEEP = {"latin", "latin-ext"}

req = urllib.request.Request(CSS_URL, headers={"User-Agent": UA})
css = urllib.request.urlopen(req, timeout=30).read().decode("utf-8")

blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
os.makedirs("fonts", exist_ok=True)

out, saved = [], {}
for subset, block in blocks:
    if subset not in KEEP:
        continue
    family = re.search(r"font-family: '([^']+)'", block).group(1)
    style = re.search(r"font-style: (\w+)", block).group(1)
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
    if url not in saved:
        name = "%s-%s-%s.woff2" % (family.lower(), style, subset)
        data = urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()
        with open(os.path.join("fonts", name), "wb") as f:
            f.write(data)
        saved[url] = name
        print("%-34s %6d bytes" % (name, len(data)))
    out.append("/* %s */\n%s" % (subset, block.replace(url, "fonts/" + saved[url])))

header = ("/* Fraunces + Archivo, self-hosted (SIL Open Font License).\n"
          "   Generated by tools/build-fonts.py - do not edit by hand. */\n")
with io.open("fonts.css", "w", encoding="utf-8", newline="\n") as f:
    f.write(header + "\n".join(out) + "\n")
print("fonts.css: %d @font-face rules, %d files" % (len(out), len(saved)))
