# -*- coding: utf-8 -*-
"""Fill the chapter-4 photo carousel ("Built so far") from a folder.

Put photos into photos/aufbau/ (any jpg/png/webp/heic from WhatsApp is fine),
then run:
    python tools/build-carousel.py

Each photo is resized and saved as assets/build/<name>.webp, and the slides
between the build-slides markers in index.html are rewritten: the two captioned
photos (the concrete base, then the finished shell) first, then the folder's
photos in file-name order. Running it again only converts new photos.
"""
import glob
import io
import os
import re
import sys

from PIL import Image, ImageOps

SRC = "photos/aufbau"
OUT = "assets/build"
MAX_W, MAX_H = 1080, 1440      # 3:4 frame, 2x for sharp phones

FIXED = [
    ('assets/ch4-slab.webp', "The freshly poured concrete base of the second building, timber stacked behind it.", "wipeA", "May 2020 · a concrete base"),
    ('assets/ch4-build.webp', "The finished shell of the second building standing under a blue sky.", "wipeB", "months later · a building"),
]
ALT = "The Cheerful Kindergarten in its early days: the yard, the buildings and the dogs."

os.makedirs(OUT, exist_ok=True)
files = sorted(f for f in glob.glob(os.path.join(SRC, "*"))
               if f.lower().endswith((".jpg", ".jpeg", ".png", ".webp", ".heic")))

slides = []
for i, f in enumerate(files, 1):
    base = re.sub(r"[^a-z0-9]+", "-", os.path.splitext(os.path.basename(f))[0].lower()).strip("-")[:48]
    dst = os.path.join(OUT, "%02d-%s.webp" % (i, base))
    if not os.path.exists(dst):
        im = ImageOps.exif_transpose(Image.open(f)).convert("RGB")
        im.thumbnail((MAX_W, MAX_H), Image.LANCZOS)
        im.save(dst, "WEBP", quality=80, method=6)
        print("converted  %s -> %s  %dx%d" % (os.path.basename(f), dst, im.width, im.height))
    w, h = Image.open(dst).size
    slides.append((dst.replace(os.sep, "/"), w, h))

html = io.open("index.html", encoding="utf-8").read()
start = "<!-- build-slides:start (generated by tools/build-carousel.py) -->"
end = "<!-- build-slides:end -->"
if start not in html or end not in html:
    sys.exit("index.html: carousel markers not found")

ind = " " * 18
rows = []
for src, alt, key, cap in FIXED:
    rows.append('%s<figure class="build-slide"><img src="%s" width="720" height="960" alt="%s" loading="lazy">'
                '<figcaption data-i18n="%s">%s</figcaption></figure>' % (ind, src, alt, key, cap))
for src, w, h in slides:
    rows.append('%s<figure class="build-slide"><img src="%s" width="%d" height="%d" alt="%s" loading="lazy"></figure>'
                % (ind, src, w, h, ALT))

block = start + "\n" + "\n".join(rows) + "\n" + ind + end
html = re.sub(re.escape(start) + r".*?" + re.escape(end), lambda m: block, html, count=1, flags=re.S)
io.open("index.html", "w", encoding="utf-8", newline="\n").write(html)
print("index.html: %d slides (%d fixed + %d from %s)" % (len(rows), len(FIXED), len(slides), SRC))
